# Generated by Django 2.1.5 on 2019-01-24 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libmgmt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='country',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='student',
            name='username',
            field=models.CharField(max_length=25),
        ),
    ]
