# Generated by Django 2.1.5 on 2019-01-28 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libmgmt', '0005_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='noofcopies',
            field=models.IntegerField(default=0),
        ),
    ]
