# Generated by Django 2.1.5 on 2019-01-28 15:57

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libmgmt', '0006_book_noofcopies'),
    ]

    operations = [
        migrations.CreateModel(
            name='BooksIssued',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.CharField(default='Y', max_length=1)),
                ('issuedate', models.DateField(default=datetime.date(2019, 1, 28))),
                ('returndate', models.DateField(null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libmgmt.Book')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libmgmt.Student')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='books_issued',
            field=models.ManyToManyField(through='libmgmt.BooksIssued', to='libmgmt.Book'),
        ),
    ]
