# Generated by Django 2.1.5 on 2019-01-29 14:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libmgmt', '0007_auto_20190128_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='published',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booksissued',
            name='issuedate',
            field=models.DateField(default=datetime.date(2019, 1, 29)),
        ),
    ]
