# Generated by Django 2.1.5 on 2019-01-30 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libmgmt', '0009_auto_20190130_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='profilepic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
